### ISSUE TITLE
 Não reconhece a entidade

### ISSUE THREAD

**Issue by johncordeiro** [bothub-it/bothub#110]
[![Screenshot_2019-09-26_17-40-08.png](https://mrkr.io/s/5d8cf7f70453705260e4e2e5/2)](https://mrkr.io/s/5d8cf7f70453705260e4e2e5/0)

Eu adicionei no analyze text uma frase que deveria entrar na entidade techday. Porém, não está reconhecendo, só está reconhecendo a intenção.

---
### More Info

**Reported by:** Júlia Stutz Souza C. de Campos (julia.stutz@ilhasoft.com.br)
**Source URL**: [https://bothub.it/enricksen/eventlead/training](https://bothub.it/enricksen/eventlead/training)

<table><tr><td><strong>Browser</strong></td><td>Chrome 76.0.3809.100</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Linux</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 738</td></tr><tr><td><strong>Zoom Level</strong></td><td>80%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.800000011920929x</td></tr></table>

**Comment by dielsonsales** [comment]
The problem is that the entity needs more training data with surrounding words for context. For example, with this training data, it works fine:

![Screen Shot 2019-10-02 at 14 06 38](https://user-images.githubusercontent.com/2501345/66065504-ed539180-e51d-11e9-8bd8-2a4203452646.png)

![Screen Shot 2019-10-02 at 14 08 52](https://user-images.githubusercontent.com/2501345/66065640-3f94b280-e51e-11e9-9dc5-852121df848d.png)
